# Generated by Django 5.1.1 on 2026-01-22 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roles', to='role_ready.industry')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'industry')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='role_ready.skillcategory')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_score', models.DecimalField(decimal_places=2, help_text='Overall readiness score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional analysis notes')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_results', to='role_ready.careerrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'unique_together': {('user', 'target_role', 'calculated_at')},
            },
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='role_ready.careerrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_roadmaps', to=settings.AUTH_USER_MODEL)),
                ('gap_result', models.OneToOneField(blank=True, help_text='Associated skill gap result', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='role_ready.skillgapresult')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'target_role')},
            },
        ),
        migrations.CreateModel(
            name='RoleSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight percentage (0-100) indicating importance for this role', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='role_ready.careerrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='role_ready.skill')),
            ],
            options={
                'ordering': ['-priority_level', '-weight'],
                'unique_together': {('role', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(help_text='Order of this step in the roadmap (1, 2, 3, ...)')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('resources', models.JSONField(blank=True, default=list, help_text='List of learning resources (URLs, books, courses, etc.)')),
                ('estimated_hours', models.IntegerField(blank=True, help_text='Estimated hours to complete this step', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='role_ready.learningroadmap')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='role_ready.skill')),
            ],
            options={
                'ordering': ['roadmap', 'step_order'],
                'unique_together': {('roadmap', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='SkillGapBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text="User's current proficiency level", max_length=20)),
                ('required_weight', models.DecimalField(decimal_places=2, help_text='Required weight for this role', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gap_level', models.CharField(choices=[('critical', 'Critical'), ('medium', 'Medium'), ('growth', 'Growth'), ('exceeded', 'Exceeded')], help_text='Severity of the skill gap', max_length=20)),
                ('gap_score', models.DecimalField(decimal_places=2, help_text='Calculated gap score for this skill', max_digits=5)),
                ('recommendations', models.TextField(blank=True, help_text='Specific recommendations for this skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_breakdowns', to='role_ready.skill')),
                ('gap_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='role_ready.skillgapresult')),
            ],
            options={
                'ordering': ['-gap_score'],
                'unique_together': {('gap_result', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('experience_notes', models.TextField(blank=True, help_text='Optional notes about experience with this skill')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='role_ready.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
