# Generated by Django 5.1.1 on 2026-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_ready', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstep',
            name='assignments',
            field=models.JSONField(blank=True, default=list, help_text='List of assignments/tasks for this step. Each assignment has title, description, and optional deliverables.'),
        ),
    ]
